### ISSUE TITLE
Error while running the eta repl

### ISSUE THREAD

**Issue by abhi18av** [typelead/eta#425]
Hi typelead team

I've been playing with the `eta` language as a compiler and making my way through the tutorials, everything looks great there. 

When I try to execute the `etlas repl` command, it gives an error

```sh

❯ etlas repl
etlas: A REPL is not supported with this compiler.

```

Could you tell me how to correct this?

I'd like to run the `repl` globally.

**Comment by rahulmutt** [comment]
It's in progress, see #130. We'll get around to it in a couple of months - currently working on making the concurrency support solid.

**Comment by abhi18av** [comment]
I hear you, but could it be corrected by changing some settings in the global config?

I notice that I don't have the ghc in path,  rather I have  to use stack ghc as an alternative .

**Comment by jstr045329** [comment]
I got the same issue:
❯ etlas repl
etlas: A REPL is not supported with this compiler.
I decided to double check etlas --version, and kept getting 1.3, not 1.4 which contains the fix. What worked for me was:

1. Removing ~/.local/bin/eta and the other eta directories,
2. Deleting /usr/local/bin/etlas,
3. Clean download of etlas from eta-lang.org (I use the etlas install. Had issues with Gradle when I used that under Ubuntu 16.04 a month ago.)
4.  $ etlas update
5.  $ etlas select latest
6.  $ etlas --version 
     This time I get the correct output:
          etlas version 1.4.0.0
          compiled using version 2.1.0.0 of the etlas-cabal library 
7.  $ etlas repl works just fine now.

**Comment by rahulmutt** [comment]
Hi @jstr045329, development on `gradle-eta` has been rapid and it's likely that the bug has been fixed. If you faced difficulty with Gradle, please try again and file a bug report [here](https://github.com/typelead/gradle-eta/issues/new) it still persists.
